alter table contracts_contract alter column government_property rename to gfe_gfp;
alter table contracts_contract add column verysmallbusinessflag varchar(1);
alter table contracts_contract add column progsourceagency varchar(2);
alter table contracts_contract add column placeofperformancezipcode varchar(10);
alter table contracts_contract alter column contract_financing rename to contractfinancing;
alter table contracts_contract add column idvpiid varchar(50);
alter table contracts_contract alter column naics_code rename to principalnaicscode;
alter table contracts_contract alter column solicitation_id rename to solicitationid;
alter table contracts_contract add column smallbusinesscompetitivenessdemonstrationprogram varchar(1);
alter table contracts_contract add column contractingofficerbusinesssizedetermination varchar(1);
alter table contracts_contract alter column contract_description rename to descriptionofcontractrequirement;
alter table contracts_contract add column educationalinstitutionflag varchar(1);
alter table contracts_contract alter column vendor_zipcode rename to zipcode;
alter table contracts_contract add column clingercohenact varchar(1);
alter table contracts_contract add column davisbaconact varchar(1);
alter table contracts_contract add column extentcompeted varchar(3);
alter table contracts_contract alter column cost_data_obtained rename to costorpricingdata;
alter table contracts_contract alter column fed_biz_opps rename to fedbizopps;
alter table contracts_contract alter column last_modified_date rename to lastmodifieddate;
alter table contracts_contract alter column vendor_country_code rename to vendorcountrycode;
alter table contracts_contract alter column vendor_ccr_exception rename to ccrexception;
alter table contracts_contract add column fiscal_year smallint;
alter table contracts_contract add column idvagencyid varchar(4);
alter table contracts_contract alter column contract_nia_code rename to nationalinterestactioncode;
alter table contracts_contract add column firm8aflag varchar(1);
alter table contracts_contract alter column number_of_actions rename to numberofactions;
alter table contracts_contract add column purchasereason varchar(1);
alter table contracts_contract alter column supports_goodness rename to contingencyhumanitarianpeacekeepingoperation;
alter table contracts_contract add column evaluatedpreference varchar(6);
alter table contracts_contract add column psc_cat varchar(2);
alter table contracts_contract add column walshhealyact varchar(1);
alter table contracts_contract alter column idv_agency_fee rename to feepaidforuseofservice;
alter table contracts_contract add column veteranownedflag varchar(1);
alter table contracts_contract add column agencyid varchar(4);
alter table contracts_contract alter column product_origin_country rename to countryoforigin;
alter table contracts_contract alter column cancellation_date rename to cancellationdate;
alter table contracts_contract add column a76action varchar(1);
alter table contracts_contract add column progsourceaccount varchar(4);
alter table contracts_contract alter column producer_type rename to manufacturingorganizationtype;
alter table contracts_contract alter column performance_based_contract rename to performancebasedservicecontract;
alter table contracts_contract add column rec_flag varchar(1) DEFAULT '';
alter table contracts_contract alter column vendor_business_name rename to vendordoingasbusinessname;
alter table contracts_contract add column apaobflag varchar(1);
alter table contracts_contract add column baobflag varchar(1);
alter table contracts_contract alter column major_program_code rename to majorprogramcode;
alter table contracts_contract add column transaction_status varchar(32);
alter table contracts_contract add column commercialitemtestprogram varchar(1);
alter table contracts_contract add column piid varchar(50);
alter table contracts_contract add column aiobflag varchar(1);
alter table contracts_contract alter column contract_action_type rename to contractactiontype;
alter table contracts_contract add column progsourcesubacct varchar(3);
alter table contracts_contract alter column modification_number rename to modnumber;
alter table contracts_contract add column research varchar(3);
alter table contracts_contract add column type_of_contract BLIMEY!!!;
alter table contracts_contract add column eeparentduns varchar(13);
alter table contracts_contract add column organizationaltype varchar(30);
alter table contracts_contract add column statutoryexceptiontofairopportunity varchar(4);
alter table contracts_contract alter column recovered_material_clause rename to recoveredmaterialclauses;
alter table contracts_contract add column claimantprogramcode varchar(3);
alter table contracts_contract add column interagencycontractingauthority varchar(1);
alter table contracts_contract alter column vendor_street_address3 rename to streetaddress3;
alter table contracts_contract alter column vendor_street_address2 rename to streetaddress2;
alter table contracts_contract alter column contract_offers_received rename to numberofoffersreceived;
alter table contracts_contract add column naobflag varchar(1);
alter table contracts_contract alter column vendor_state rename to state;
alter table contracts_contract add column servicecontractact varchar(1);
alter table contracts_contract alter column purchase_card_as_payment rename to purchasecardaspaymentmethod;
alter table contracts_contract alter column place_location_code rename to locationcode;
alter table contracts_contract alter column maximum_date rename to ultimatecompletiondate;
alter table contracts_contract alter column transaction_number rename to transactionnumber;
alter table contracts_contract alter column contract_competitiveness rename to extentcompeted;
alter table contracts_contract add column haobflag varchar(1);
alter table contracts_contract alter column place_state_code rename to statecode;
alter table contracts_contract add column solicitationprocedures varchar(5);
alter table contracts_contract add column womenownedflag varchar(1);
alter table contracts_contract alter column vender_phone rename to phoneno;
alter table contracts_contract add column srdvobflag varchar(1);
alter table contracts_contract alter column statutory_authority rename to otherstatutoryauthority;
alter table contracts_contract alter column consolidated_contract rename to consolidatedcontract;
alter table contracts_contract alter column requesting_office_id rename to fundingrequestingofficeid;
alter table contracts_contract alter column contract_set_aside rename to typeofsetaside;
alter table contracts_contract add column placeofperformancecountrycode varchar(3);
alter table contracts_contract alter column dod_system_code rename to systemequipmentcode;
alter table contracts_contract add column tribalgovernmentflag varchar(1);
alter table contracts_contract alter column subcontract_plan rename to subcontractplan;
alter table contracts_contract alter column vendor_city rename to city;
alter table contracts_contract alter column contracting_office_id rename to contractingofficeid;
alter table contracts_contract add column useofepadesignatedproducts varchar(1);
alter table contracts_contract add column maj_agency_cat varchar(2);
alter table contracts_contract add column hbcuflag varchar(1);
alter table contracts_contract alter column obligated_amount rename to obligatedamount;
alter table contracts_contract add column stategovernmentflag varchar(1);
alter table contracts_contract add column pop_cd varchar(4);
alter table contracts_contract add column commercialitemacquisitionprocedures varchar(1);
alter table contracts_contract alter column current_amount rename to baseandexercisedoptionsvalue;
alter table contracts_contract alter column contract_pricing_type rename to typeofcontractpricing;
alter table contracts_contract alter column vendor_fax rename to faxno;
alter table contracts_contract alter column id rename to record_id;
alter table contracts_contract add column nonprofitorganizationflag varchar(1);
alter table contracts_contract alter column it_commercial_availability rename to informationtechnologycommercialitemcategory;
alter table contracts_contract alter column multiyear_contract rename to multiyearcontract;
alter table contracts_contract add column hubzoneflag varchar(1);
alter table contracts_contract add column minorityownedbusinessflag varchar(1);
alter table contracts_contract alter column vendor_parent_duns rename to parentdunsnumber;
alter table contracts_contract add column lettercontract varchar(1);
alter table contracts_contract alter column contracting_agency_id rename to contractingofficeagencyid;
alter table contracts_contract alter column product_service_code rename to productorservicecode;
alter table contracts_contract add column mod_parent varchar(100);
alter table contracts_contract alter column cotr_name rename to cotrname;
alter table contracts_contract add column unique_transaction_id varchar(32);
alter table contracts_contract alter column signed_date rename to signeddate;
alter table contracts_contract add column localgovernmentflag varchar(1);
alter table contracts_contract alter column renewal_date rename to renewaldate;
alter table contracts_contract add column sdbflag varchar(1);
alter table contracts_contract add column federalgovernmentflag varchar(1);
alter table contracts_contract add column seatransportation varchar(1);
alter table contracts_contract alter column completion_date rename to currentcompletiondate;
alter table contracts_contract alter column cotr_other_name rename to alternatecotrname;
alter table contracts_contract add column fundedbyforeignentity varchar(1);
alter table contracts_contract alter column vendor_duns rename to dunsnumber;
alter table contracts_contract alter column contract_bundling_type rename to contractbundling;
alter table contracts_contract alter column vendor_street_address rename to streetaddress;
alter table contracts_contract alter column requesting_agency_id rename to fundingrequestingagencyid;
alter table contracts_contract alter column place_district rename to congressionaldistrict;
alter table contracts_contract alter column vendor_name rename to vendorname;
alter table contracts_contract add column idvmodificationnumber varchar(25);
alter table contracts_contract add column competitiveprocedures varchar(3);
alter table contracts_contract alter column vendor_employees rename to numberofemployees;
alter table contracts_contract alter column maximum_amount rename to baseandalloptionsvalue;
alter table contracts_contract alter column product_origin rename to placeofmanufacture;
alter table contracts_contract add column placeofperformancecongressionaldistrict varchar(6);
alter table contracts_contract alter column modification_reason rename to reasonformodification;
alter table contracts_contract alter column vendor_district rename to vendor_cd;
alter table contracts_contract alter column contract_nocompete_reason rename to reasonnotcompeted;
alter table contracts_contract add column shelteredworkshopflag varchar(1);
alter table contracts_contract alter column vendor_annual_revenue rename to annualrevenue;
alter table contracts_contract add column hospitalflag varchar(1);
alter table contracts_contract alter column effective_date rename to effectivedate;
alter table contracts_contract alter column agency_id rename to agencyid;
alter table contracts_contract alter column price_difference rename to priceevaluationpercentdifference;
alter table contracts_contract alter column cas_clause rename to costaccountingstandardsclause;
alter table contracts_contract add column saaobflag varchar(1);
