#!/bin/bash

server="http://my.followthemoney.org/sunlight/"
date=2009-09-01

if [ -n "$1" ]; then
   date=$1
fi

dest=/home/datacommons/var/nimsp/$date
if [ $(uname) = 'Darwin' ]; then
   dest=/home/$USER/projects/datacommons/var/nimsp/$date
fi

if [ ! -d "$dest" ]; then
  mkdir $dest || exit 1
fi

cd $dest

for f in BallotMeasures.txt BallotSupport.txt Candidates.txt CatCodes.txt Committees.txt Contributions.txt Contributors.txt ExpenditurePayee.txt ExpenditureTarget.txt ExpenditureTransaction.txt LobbyistClient.txt Lobbyist.txt OfficeCodes.txt OfficeSeats.txt PartyLookup.txt RecipientReportsBundle.txt Recipients.txt States.txt StateYearReports.txt; do
   gz=$f.gz
   wget --user sunlight --password labs\!\# $server/$date/$gz -O $gz
   if [ -s $gz ]; then
      gunzip -c $gz | dos2unix > $f
   elif [ -f $gz ]; then
      rm $gz
   fi
done

sql=Update-$date.sql
wget --user sunlight --password labs\!\# $server/$date/$sql -O $sql
dos2unix $sql



    
