create table whitehouse_visitor_logs (
        id serial primary key not null,
        last_name varchar(64),
        first_name varchar(64),
        middle_name varchar(64),
        visit_id varchar(10),
        badge_number varchar(10),
        access_type varchar(3),
        arrived_at timestamp,
        where_arrived varchar(64),
        departed_at timestamp,
        where_departed varchar(64),
        appt_made_on date,
        appt_starts_at timestamp,
        appt_ends_at timestamp,
        appt_canceled_at timestamp,
        num_people integer,
        updated_by varchar(32),
        appt_entered_at_computer varchar(32),
        appt_updated_at timestamp,
        appt_created_by varchar(32),
        visitee_last_name varchar(64),
        visitee_first_name varchar(64),
        meeting_building varchar(32),
        meeting_room varchar(32),
        caller_last_name varchar(64),
        caller_first_name varchar(64),
        caller_room varchar(64),
        description text,
        released_on date
);

