alter table epa_echo_penalty alter column enfops drop not null;
alter table epa_echo_case_identifier alter column actsepa drop not null;
alter table epa_echo_case_identifier alter column id type bigint;
alter table epa_echo_penalty alter column enfocnu drop not null;
alter table epa_echo_facility alter column enfocnu drop not null;
alter table epa_echo_penalty drop CONSTRAINT epa_echo_penalty_pkey;
alter table epa_echo_penalty alter column id type bigint;
alter table epa_echo_facility alter column id type bigint;
alter table epa_echo_facility alter column enfocnu drop not null;
alter table epa_echo_facility drop CONSTRAINT epa_echo_facility_pkey;
alter table epa_echo_facility alter COLUMN fclasic drop not null;
alter table epa_echo_facility alter COLUMN fcltpst drop not null;
alter table epa_echo_facility alter column fcltyad drop not null;
alter table epa_echo_facility alter column fcltcit drop not null;
alter table epa_echo_facility alter column fcltynm drop not null;
alter table epa_echo_facility alter column fcltstc drop not null;
alter table epa_echo_defendant alter column enfocnu drop not null;
alter table epa_echo_defendant drop CONSTRAINT epa_echo_defendant_pkey;
alter table epa_echo_defendant ALTER COLUMN id type bigint;
alter table epa_echo_milestone alter column enfocnu drop not null;
alter table epa_echo_milestone drop CONSTRAINT epa_echo_milestone_pkey;
alter table epa_echo_milestone ALTER COLUMN id type bigint;
