from helpers import nullable_float, splitCode, transformFlag, nullable, \
        nullable_int, agency_name_lookup, recovery_act, datestamp

FPDS_FIELDS = [
('unique_transaction_id', None),
('transaction_status', None),
('obligatedamount', nullable_float),
('baseandexercisedoptionsvalue', nullable_float),
('baseandalloptionsvalue', nullable_float),
('maj_agency_cat', splitCode),
('mod_agency', splitCode),
('maj_fund_agency_cat', splitCode),
('contractingofficeagencyid', splitCode),
('contractingofficeid', None),
('fundingrequestingagencyid', splitCode),
('fundingrequestingofficeid', None),
('fundedbyforeignentity', splitCode),
('signeddate', nullable),
('effectivedate', nullable),
('currentcompletiondate', nullable),
('ultimatecompletiondate', nullable),
('lastdatetoorder', None),
('contractactiontype', splitCode),
('reasonformodification', splitCode),
('typeofcontractpricing', splitCode),
('priceevaluationpercentdifference', None),
('subcontractplan', splitCode),
('type_of_contract', splitCode),
('lettercontract', splitCode),
('multiyearcontract', transformFlag),
('performancebasedservicecontract', splitCode),
('majorprogramcode', None),
('contingencyhumanitarianpeacekeepingoperation', splitCode),
('contractfinancing', splitCode),
('costorpricingdata', splitCode),
('costaccountingstandardsclause', splitCode),
('descriptionofcontractrequirement', None),
('purchasecardaspaymentmethod', transformFlag),
('numberofactions', nullable_int),
('nationalinterestactioncode', splitCode),
('progsourceagency', splitCode),
('progsourceaccount', splitCode),
('progsourcesubacct', splitCode),
('account_title', None),
('rec_flag', recovery_act),
('typeofidc', None),
('multipleorsingleawardidc', None),
('programacronym', None),
('vendorname', None),
('vendoralternatename', None),
('vendorlegalorganizationname', None),
('vendordoingasbusinessname', None),
('divisionname', None),
('divisionnumberorofficecode', None),
('vendorenabled', None),
('vendorlocationdisableflag', transformFlag),
('ccrexception', None),
('streetaddress', None),
('streetaddress2', None),
('streetaddress3', None),
('city', None),
('state', splitCode),
('zipcode', None),
('vendorcountrycode', None),
('vendor_state_code', None),
('vendor_cd', splitCode),
('congressionaldistrict', None),
('vendorsitecode', None),
('vendoralternatesitecode', None),
('dunsnumber', None),
('parentdunsnumber', None),
('phoneno', None),
('faxno', None),
('registrationdate', nullable),
('renewaldate', nullable),
('mod_parent', None),
('locationcode', None),
('statecode', splitCode),
('pop_state_code', None),
('placeofperformancecountrycode', splitCode),
('placeofperformancezipcode', None),
('pop_cd', splitCode),
('placeofperformancecongressionaldistrict', None),
('psc_cat', splitCode),
('productorservicecode', splitCode),
('systemequipmentcode', splitCode),
('claimantprogramcode', splitCode),
('principalnaicscode', splitCode),
('informationtechnologycommercialitemcategory', splitCode),
('gfe_gfp', transformFlag),
('useofepadesignatedproducts', splitCode),
('recoveredmaterialclauses', splitCode),
('seatransportation', first_char),
('contractbundling', splitCode),
('consolidatedcontract', transformFlag),
('countryoforigin', splitCode),
('placeofmanufacture', splitCode),
('manufacturingorganizationtype', None),
('agencyid', splitCode),
('piid', None),
('modnumber', None),
('transactionnumber', None),
('fiscal_year', nullable_int),
('idvagencyid', None),
('idvpiid', None),
('idvmodificationnumber', None),
('solicitationid', None),
('extentcompeted', splitCode),
('reasonnotcompeted', splitCode),
('numberofoffersreceived', nullable_int),
('commercialitemacquisitionprocedures', splitCode),
('commercialitemtestprogram', transformFlag),
('smallbusinesscompetitivenessdemonstrationprogram', transformFlag),
('a76action', transformFlag),
('competitiveprocedures', splitCode),
('solicitationprocedures', splitCode),
('typeofsetaside', splitCode),
('localareasetaside', None),
('evaluatedpreference', splitCode),
('fedbizopps', None),
('research', splitCode),
('statutoryexceptiontofairopportunity', splitCode),
('organizationaltype', None),
('numberofemployees', nullable_int),
('annualrevenue', nullable_float),
('firm8aflag', transformFlag),
('hubzoneflag', transformFlag),
('sdbflag', transformFlag),
('shelteredworkshopflag', transformFlag),
('hbcuflag', transformFlag),
('educationalinstitutionflag', transformFlag),
('womenownedflag', transformFlag),
('veteranownedflag', transformFlag),
('srdvobflag', transformFlag),
('localgovernmentflag', transformFlag),
('minorityinstitutionflag', transformFlag),
('aiobflag', splitCode),
('stategovernmentflag', transformFlag),
('federalgovernmentflag', transformFlag),
('minorityownedbusinessflag', transformFlag),
('apaobflag', transformFlag),
('tribalgovernmentflag', transformFlag),
('baobflag', transformFlag),
('naobflag', transformFlag),
('saaobflag', transformFlag),
('nonprofitorganizationflag', transformFlag),
('haobflag', transformFlag),
('verysmallbusinessflag', transformFlag),
('hospitalflag', transformFlag),
('contractingofficerbusinesssizedetermination', splitCode),
('receivescontracts', splitCode),
('receivesgrants', splitCode),
('receivescontractsandgrants', splitCode),
('walshhealyact', transformFlag),
('servicecontractact', transformFlag),
('davisbaconact', transformFlag),
('clingercohenact', transformFlag),
('otherstatutoryauthority', None),
('interagencycontractingauthority', splitCode),
('isserviceprovider', transformFlag),

]

CALCULATED_FPDS_FIELDS = [
        ('agency_name', 'agencyid', agency_name_lookup),
        ('contracting_agency_name', 'contractingofficeagencyid', agency_name_lookup),
        ('requesting_agency_name', 'fundingrequestingagencyid', agency_name_lookup),
        ('imported_on', None, datestamp),
]





        
    
    
    
