CREATE TABLE IF NOT EXISTS candidate (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cid TEXT,
    cycle TEXT,
    fec_cand_id TEXT,
    first_last_p TEXT,
    party TEXT,
    dist_id_run_for TEXT,
    dist_id_curr TEXT,
    curr_cand TEXT,
    cycle_cand TEXT,
    crp_ico TEXT,
    recip_code TEXT,
    no_pacs TEXT
);

CREATE TABLE IF NOT EXISTS committee (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cmte_id TEXT,
    cycle TEXT,
    pac_short TEXT,
    affiliate TEXT,
    ult_org TEXT,
    recip_id TEXT,
    recip_code TEXT,
    fec_cand_id TEXT,
    party TEXT,
    prim_code TEXT,
    source TEXT,
    sensitive TEXT,
    is_foreign INTEGER,
    active INTEGER
);

CREATE TABLE IF NOT EXISTS individual_contribution (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fec_trans_id TEXT,
    cycle TEXT,
    contrib_id TEXT,
    contrib TEXT,
    recip_id TEXT,
    org_name TEXT,
    ult_org TEXT,
    real_code TEXT,
    datestamp TEXT,
    amount INTEGER,
    street TEXT,
    city TEXT,
    state TEXT,
    zipcode TEXT,
    recip_code TEXT,
    type TEXT,
    cmte_id TEXT,
    other_id TEXT,
    gender TEXT,
    fec_occ_emp TEXT,
    microfilm TEXT,
    occ_ef TEXT,
    emp_ef TEXT,
    source TEXT
);

CREATE TABLE IF NOT EXISTS pac2pac_contribution (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    fec_rec_no TEXT,
    cycle TEXT,
    filer_id TEXT,
    donor_cmte TEXT,
    contrib_lend_trans TEXT,
    city TEXT,
    state TEXT,
    zipcode TEXT,
    fec_occ_emp TEXT,
    prim_code TEXT,
    datestamp TEXT,
    amount INTEGER,
    recip_id TEXT,
    party TEXT,
    other_id TEXT,
    recip_code TEXT,
    recip_prim_code TEXT,
    amend TEXT,
    report TEXT,
    pg TEXT,
    microfilm TEXT,
    type TEXT,
    real_code TEXT,
    source TEXT
);

CREATE TABLE IF NOT EXISTS pac_contribution (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    cycle TEXT,
    fec_rec_no TEXT,
    pac_id TEXT,
    cid TEXT,
    amount INTEGER,
    datestamp TEXT,
    real_code TEXT,
    type TEXT,
    di TEXT,
	fec_cand_id TEXT
);