drop table if exists tmp_cc_cleaned;
create table tmp_cc_cleaned as
    select 
        id,
        import_reference_id,
        cycle,
        transaction_namespace,
        transaction_id,
        transaction_type,
        filing_id,
        is_amendment,
        amount,
        date,
        regexp_replace(regexp_replace(contributor_name, '\r', ' '), '\n', ' ') as contributor_name,
        contributor_ext_id,
        contributor_type,
        regexp_replace(regexp_replace(contributor_occupation, '\r', ' '), '\n', ' ') as contributor_occupation,
        regexp_replace(regexp_replace(contributor_employer, '\r', ' '), '\n', ' ') as contributor_employer,
        contributor_gender,
        regexp_replace(regexp_replace(contributor_address, '\r', ' '), '\n', ' ') as contributor_address,
        regexp_replace(regexp_replace(contributor_city, '\r', ' '), '\n', ' ') as contributor_city,
        contributor_state,
        contributor_zipcode,
        contributor_category,
        regexp_replace(regexp_replace(organization_name, '\r', ' '), '\n', ' ') as organization_name,
        organization_ext_id,
        regexp_replace(regexp_replace(parent_organization_name, '\r', ' '), '\n', ' ') as parent_organization_name,
        parent_organization_ext_id,
        regexp_replace(regexp_replace(recipient_name, '\r', ' '), '\n', ' ') as recipient_name,
        recipient_ext_id,
        regexp_replace(regexp_replace(recipient_party, '\r', ' '), '\n', ' ') as recipient_party,
        recipient_type,
        recipient_state,
        recipient_state_held,
        recipient_category,
        regexp_replace(regexp_replace(committee_name, '\r', ' '), '\n', ' ') as committee_name,
        committee_ext_id,
        committee_party,
        candidacy_status,
        district,
        district_held,
        seat,
        seat_held,
        seat_status,
        seat_result
    from contribution_contribution;
commit;
