_transaction_type_descriptions = {
    '10': "Non-Federal Receipt from Persons - Levin Account (L-1A)",
    '11': "Tribal Contribution",
    '12': "Non-Federal Other Receipt - Levin Account (L-2)",
    '13': "Inaugural Donation Accepted",
    '15': "Contribution",
    '15c': "Contribution from Candidate",
    '15e': "Earmarked Contribution",
    '15f': "Loans forgiven by Candidate",
    '15i': "Earmarked Intermediary In",
    '15j': "Memo (Filer's Percentage of Contribution Given to Join Fundraising Committee)",
    '15t': "Earmarked Intermediary Treasury In",
    '15z': "In-Kind Contribution Received from Registered Filer",
    '16c': "Loans Received from the Candidate",
    '16f': "Loans Received from Banks",
    '16g': "Loan from Individual",
    '16h': "Loan from from Registered Filers",
    '16j': "Loan Repayments from Individual",
    '16k': "Loan Repayments from from Registered Filer",
    '16l': "Loan Repayments Received from Unregistered Entity",
    '16r': "Loans Received from Registered Filers",
    '16u': "Loan Received from Unregistered Entity",
    '17r': "Contribution Refund Received from Registered Entity",
    '17u': "Refunds/Rebates/Returns Received from Unregistered Entity",
    '17y': "Refunds/Rebates/Returns from Individual or Corporation",
    '17z': "Refunds/Rebates/Returns from Candidate or Committee",
    '18g': "Transfer In Affiliated",
    '18h': "Honorarium Received",
    '18j': "Memo (Filer's Percentage of Contribution Given to Join Fundraising Committee)",
    '18k': "Contribution Received from Registered Filer",
    '18l': "Bundled Contribution",
    '18s': "Receipts from Secretary of State",
    '18u': "Contribution Received from Unregistered Committee",
    '19': "Electioneering Communication Donation Received",
    '19j': "Memo (Electioneering Communication Percentage of Donation Given to Join Fundraising Committee)",
    '20': "Disbursement - Exempt from Limits",
    '20a': "Non-Federal Disbursement - Levin Account (L-4A) Voter Registration",
    '20b': "Non-Federal Disbursement - Levin Account (L-4B) Voter Identification",
    '20c': "Loan Repayments Made to Candidate",
    '20d': "Non-Federal Disbursement - Levin Account (L-4D) Generic Campaign",
    '20f': "Loan Repayments Made to Banks",
    '20g': "Loan Repayments Made to Individual",
    '20r': "Loan Repayments Made to Registered Filer",
    '20v': "Non-Federal Disbursement - Levin Account (L-4C) Get Out The Vote",
    '22g': "Loan to Individual",
    '22h': "Loan to Candidate or Committee",
    '22j': "Loan Repayment to Individual",
    '22k': "Loan Repayment to Candidate or Committee",
    '22l': "Loan Repayment to Bank",
    '22r': "Contribution Refund to Unregistered Entity",
    '22u': "Loan Repaid to Unregistered Entity",
    '22x': "Loan Made to Unregistered Entity",
    '22y': "Contribution Refund to Individual",
    '22z': "Contribution Refund to Candidate or Committee",
    '23y': "Inaugural Donation Refund",
    '24a': "Independent Expenditure Against",
    '24c': "Coordinated Expenditure",
    '24e': "Independent Expenditure For",
    '24f': "Communication Cost for Candidate (C7)",
    '24g': "Transfer Out Affiliated",
    '24h': "Honorarium to Candidate",
    '24i': "Earmarked Intermediary Out",
    '24k': "Contribution Made to Non-Affiliated",
    '24n': "Communication Cost Against Candidate (C7)",
    '24p': "Contribution Made to Possible Candidate",
    '24r': "Election Recount Disbursement",
    '24t': "Earmarked Intermediary Treasury Out",
    '24u': "Contribution Made to Unregistered Entity",
    '24z': "In-Kind Contribution Made to Registered Filer",
    '28l': "Refund of Bundled Contribution",
    '29': "Electioneering Communication Disbursement or Obligation",
}

def add_transaction_type_description(result_iter):
    for row in result_iter:
        row.transaction_type_description = _transaction_type_descriptions.get(row.transaction_type, '')
        yield row
