#!/bin/bash

#########################################################################
# load-nimsp-update
#
# Load a NIMSP update release into mysql. 
#########################################################################

program=$(basename $0)
USERNAME=datacommons
DBNAME=nimsp


set -e

function usage {
    cat <<EOF
Usage: $program -s DIRECTORY [OPTION]...

Options:
  -d DBNAME     Database (default $DBNAME)
  -s DIRECTORY  Data directory to load from (required)
  -p PASSWORD   Database password
  -U USERNAME   Database user name (default $USERNAME)

Help:
  --help        Print this help, then exit
EOF
    exit $1;
}

if [ -n "$1" ] && [ -n "$(echo $1 | grep -E '^--?h(e(lp?)?)?$')" ]; then
    usage 0;
fi

while getopts ":d:hs:p:U:" opt; do
    case $opt in
	d) DBNAME=$OPTARG;;
	h) usage 0;;
	p) PASSWD=$OPTARG;;
	s) src=$OPTARG;;
	U) USERNAME=$OPTARG;;
	*) usage 1;;
    esac
done
if [ -z "$src" ]; then
    echo "-s DIRECTORY is required" >&2
    exit 1
elif [ ! -d "$src" ]; then
    echo "No such directory $src" >&2
    exit 1
fi 

update=${src}/Update-20[0-9][0-9]-[01][0-9]-[0123][0-9].sql 
if [ ! -f $update ]; then
    echo "No such file $update" >&2
    exit 1
fi

if [ -z "$PASSWD" ]; then
    echo -n 'password: ' >&2
    read PASSWD
fi


set -e
echo Loading $update
mysql -u $USERNAME --password=$PASSWD $DBNAME < $update

for txt in $src/*.txt; do
    gz=$txt.gz
    if [ ! -f $txt ] && [ -f $gz ]; then
       gunzip -c $gz
    fi
    if [ -f $txt ]; then
	echo Loading $txt
	mysql -u $USERNAME --password=$PASSWD -e "LOAD DATA LOCAL INFILE '$txt' REPLACE INTO TABLE $t IGNORE 1 LINES;" $DBNAME
    fi
done

    
